package ee.schimke.composeai.designparity

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * `PageBackdropManifest` — a **design page imported as a backdrop**, with every component instance
 * on it linked back to the code that implements it.
 *
 * This is a **foreign contract**: the producer is design-parity's Figma page importer, published
 * independently to npm as `@design-parity/page-backdrop`. Source of truth is that package's
 * `schema/page-backdrop.schema.json` (shipped in the tarball); the prose spec is its
 * `docs/page-backdrop-contract.md`. We are one consumer among several — the design tool decides
 * nothing about how we draw this, and neither does the producer.
 *
 * ## Hand-written, deliberately
 *
 * [SpatialScene][ee.schimke.composeai.xr.SpatialScene] is generated by
 * `scripts/codegen/gen-spatial-scene.mjs` from a schema in *this* repo. This mirror is not, because
 * its schema lives in another repository on its own release cadence — vendoring a copy here to
 * generate from would create a second source of truth, which is the one thing a wire contract
 * cannot have. Instead the shapes are hand-written and pinned by `PageBackdropParseTest`, which
 * parses the producer's own committed fixture. If the producer changes the shape, that test fails.
 *
 * ## Why the producer's data and not our own render
 *
 * A placement carries a [Placement.previewId]. That is the whole point of consuming this rather
 * than the HTML viewer the producer also ships: given a preview id and the placement's
 * [Placement.bounds], we can render the component **at the placement's exact size** instead of
 * scaling a fixed-size screenshot to fit. The producer cannot do that — it has no renderer.
 */
public const val PAGE_BACKDROP_VERSION: Int = 1

/**
 * Whether a manifest at [version] is one we can read.
 *
 * Deliberately not `== PAGE_BACKDROP_VERSION`. The producer ships independently and bumps only for
 * *breaking* shape changes, adding optional fields without a bump — so requiring equality would
 * make every routine additive release look like a break. Newer-but-additive manifests parse fine
 * because [PageBackdropJson] ignores unknown keys.
 */
public fun supportsPageBackdropVersion(version: Int): Boolean = version in 1..PAGE_BACKDROP_VERSION

/**
 * The decoder every consumer of this contract should use.
 *
 * `ignoreUnknownKeys` is **required by the contract**, not a convenience: a manifest written by a
 * newer producer will carry fields this build has never heard of, and refusing to parse it would
 * turn every additive upstream release into an outage here.
 */
public val PageBackdropJson: Json = Json {
  ignoreUnknownKeys = true
  explicitNulls = false
}

/**
 * An axis-aligned rectangle in the page's **frame-local design units (dp)**, origin at the frame's
 * top-left.
 *
 * Not image pixels: the backdrop PNG is exported at some [BackdropImage.scale], so pinning geometry
 * to the unscaled frame keeps the manifest valid across re-exports. Position by ratio against
 * [BackdropPage.frame] and no density arithmetic is needed.
 */
@Serializable
public data class PageRect(val x: Double, val y: Double, val width: Double, val height: Double)

/** How a placement was linked to code. */
@Serializable
public enum class PlacementLink {
  /** Figma Code Connect — the machine link. */
  @SerialName("code-connect") CODE_CONNECT,

  /** An explicit entry in the repo's `design-map.json`. */
  @SerialName("manifest") MANIFEST,

  /** Best-effort name match; always low confidence. */
  @SerialName("convention") CONVENTION,

  /**
   * Nothing matched. Not an omission — a part of the screen with no code behind it is the finding a
   * whole-screen view exists to surface, so the producer keeps it.
   */
  @SerialName("unlinked") UNLINKED,
}

/** How much to trust a placement's `code`. */
@Serializable
public enum class PlacementConfidence {
  @SerialName("high") HIGH,
  @SerialName("low") LOW,
}

/** One component instance on the page, and the code it maps to. */
@Serializable
public data class Placement(
  /** Node id of the instance on the page. */
  val nodeId: String,
  /** The instance's layer name, e.g. `"Button/Primary"`. */
  val name: String,
  /** Node id of the instance's main component, when the source reports one. */
  val componentId: String? = null,
  /** Node id of the main component's variant set — where Code Connect usually sits. */
  val componentSetId: String? = null,
  /** Where the instance sits, in frame-local design units. */
  val bounds: PageRect,
  /** Nesting depth below the page frame; `0` for a top-level instance. */
  val depth: Int = 0,
  /**
   * The instance's own design ref, `"figma:<fileKey>/<nodeId>"` — what lets a hotspot deep-link
   * into the design tool even where no code implements it.
   *
   * **Nullable on purpose.** The producer emits it for every placement, linked or not, but only
   * since the release that introduced it; manifests written by an earlier producer have no `ref` at
   * all, and a required field here would make those a hard parse failure rather than a degraded
   * read. Prefer [PageBackdropManifest.refFor], which fills the gap from the manifest's `fileKey` —
   * the same string the producer would have written.
   */
  val ref: String? = null,
  /**
   * Code handle, e.g. `"ui/Button.kt#PrimaryButton"`. Null when [link] is [PlacementLink.UNLINKED].
   */
  val code: String? = null,
  /**
   * Fully-qualified preview id, when the producer's `design-map.json` names one. This is what lets
   * us render the component ourselves rather than showing a baked screenshot.
   */
  val previewId: String? = null,
  val link: PlacementLink,
  /** Null when unlinked. Stated by the producer so we don't hardcode which methods are weak. */
  val confidence: PlacementConfidence? = null,
  /** Which ref carried the link — the set, the main component, or the instance. */
  val matchedRef: String? = null,
) {
  /** Whether this placement can be rendered by us, i.e. it names a preview we could ask for. */
  public val isRenderable: Boolean
    get() = previewId != null
}

/** The exported backdrop image for a page. */
@Serializable
public data class BackdropImage(
  /** Path to the PNG, relative to the manifest file. */
  val uri: String,
  /** Export scale; `2` means the PNG is 2× [BackdropPage.frame]. */
  val scale: Double,
)

/** The page frame's size in design units — the coordinate space every [PageRect] lives in. */
@Serializable public data class FrameSize(val width: Double, val height: Double)

/** One imported page. */
@Serializable
public data class BackdropPage(
  /** Stable slug, unique within the manifest; also the backdrop PNG's basename. */
  val id: String,
  /** The frame's layer name in the design file. */
  val name: String,
  /** Node id of the page frame. */
  val nodeId: String,
  val frame: FrameSize,
  val image: BackdropImage,
  /** Ordered top-left first, so a re-import diffs cleanly. */
  val placements: List<Placement> = emptyList(),
) {
  /** Instances with code behind them. */
  public val linked: List<Placement>
    get() = placements.filter { it.link != PlacementLink.UNLINKED }

  /** Instances with no code behind them — the coverage gaps. */
  public val unlinked: List<Placement>
    get() = placements.filter { it.link == PlacementLink.UNLINKED }
}

/** A committed page-backdrop import. */
@Serializable
public data class PageBackdropManifest(
  val version: Int,
  /** Design source. Only Figma exposes a page-level read API today. */
  val source: String = "figma",
  /** The design-tool file the pages came from. */
  val fileKey: String,
  val pages: List<BackdropPage> = emptyList(),
) {
  /** Whether this build understands the manifest's version. */
  public val isSupported: Boolean
    get() = supportsPageBackdropVersion(version)

  /**
   * The design ref for [placement], deriving it when the producer didn't write one.
   *
   * Use this rather than [Placement.ref] directly. A ref is `"figma:<fileKey>/<nodeId>"`, and both
   * halves are already here — so a manifest from a producer predating the field loses nothing but
   * the literal string, and reconstructing it is exact rather than a guess.
   *
   * This is the tolerance a consumer owes a contract whose producer releases separately. The
   * version-range check covers *breaking* changes; this covers the ordinary case of running against
   * an older producer, which no version bump announces.
   */
  public fun refFor(placement: Placement): String =
    placement.ref ?: "figma:$fileKey/${placement.nodeId}"
}
