package ee.schimke.composeai.daemon

/**
 * Reflective shim that clears Compose Multiplatform Resources' process-wide string-item cache. The
 * cache is the private static field `StringResourcesUtilsKt.stringItemsCache` (an `AsyncCache<String,
 * StringItem>`), keyed by `path/offset-size` and populated by the *first*
 * [org.jetbrains.compose.resources.ResourceReader] to answer a given key.
 *
 * **Why this exists.** `:data-pseudolocale-connector-desktop` wraps [LocalResourceReader] so every
 * `stringResource(...)` lookup returns the pseudolocalised accent / bidi form. But CMP's cache
 * snapshots the *value* returned by the reader the first time the key is requested, so a prior
 * non-pseudo render in the same JVM warms the cache with plain strings and the next pseudo render
 * receives those plain strings from the cache instead of going through the wrapped reader. Same
 * issue when switching between `en-XA` and `ar-XB`. The `DesktopHost` reuses the same JVM /
 * classloader across requests, so this happens any time a daemon serves a mixed render sequence.
 *
 * **Approach.** [clearStringResourcesCacheBestEffort] reaches into the
 * `org.jetbrains.compose.resources.StringResourcesUtilsKt` class via reflection, fetches the
 * `stringItemsCache` field, drills into its internal `cache: Map<…>` and calls `Map.clear()` on the
 * backing map. The traversal goes through `AsyncCache.access$getCache$p(...)` which is a synthetic
 * public method generated by the Kotlin compiler for the private `cache` field — these are stable
 * across CMP patch versions in the 1.10.x line.
 *
 * **Failure mode.** Any reflective failure (CMP renames the field, splits the cache, removes the
 * synthetic accessor in a future major version) is swallowed and returns `false`, letting the
 * caller fall back to the documented limitation in [PseudolocalizingResourceReader] ("restart the
 * JVM between modes"). We never crash a render over a reflective miss; we just degrade to the
 * documented behaviour.
 *
 * **Not a long-term solution.** Tracked at compose-ai-tools#1360 finding #3 — the right fix is for
 * CMP to expose a per-renderer cache scope, at which point this whole shim goes away. Until then,
 * this reflective workaround eliminates the silent no-op the issue calls out.
 */
internal object PseudolocaleResourceCache {

  /**
   * Class name of the Kotlin top-level file that holds the cache. Held as a literal string so the
   * keep-rules in consuming apps don't need to know about it.
   */
  private const val UTILS_CLASS = "org.jetbrains.compose.resources.StringResourcesUtilsKt"

  /**
   * Field name on [UTILS_CLASS] holding the `AsyncCache<String, StringItem>` instance. Matches the
   * declaration in CMP 1.10.x; if a future CMP version renames this field the reflective lookup
   * fails gracefully and we degrade to the documented "restart the JVM" caveat.
   */
  private const val CACHE_FIELD = "stringItemsCache"

  /**
   * Field name inside `AsyncCache` holding the actual backing `Map<K, Deferred<V>>`. Private in
   * source but emitted as a regular field by kotlinc; readable via setAccessible.
   */
  private const val ASYNC_CACHE_MAP_FIELD = "cache"

  /**
   * Clear the cache. Returns `true` on success, `false` if reflection couldn't find the cache (CMP
   * version drift) — callers can log + continue. Never throws.
   *
   * Safe to call from any thread; the underlying `Map.clear()` is a single instruction the JVM
   * publishes promptly enough that subsequent `getOrLoad` callers see an empty map. Concurrent
   * `getOrLoad` calls during the clear might still observe a transient value; we don't try to
   * synchronize against `AsyncCache.mutex` because (a) it's a `kotlinx.coroutines.sync.Mutex` (not a
   * `java.util.concurrent.locks.Lock` — no synchronous `lock()` we can call from outside a
   * coroutine context), and (b) the renderer issues renders sequentially anyway.
   */
  fun clearStringResourcesCacheBestEffort(): Boolean {
    return try {
      val utilsClass = Class.forName(UTILS_CLASS)
      val cacheField =
        utilsClass.getDeclaredField(CACHE_FIELD).apply { isAccessible = true }
      val asyncCache = cacheField.get(null) ?: return false
      val mapField =
        asyncCache.javaClass.getDeclaredField(ASYNC_CACHE_MAP_FIELD).apply { isAccessible = true }
      val map = mapField.get(asyncCache) as? MutableMap<*, *> ?: return false
      map.clear()
      true
    } catch (_: ReflectiveOperationException) {
      false
    } catch (_: ClassCastException) {
      false
    } catch (_: SecurityException) {
      false
    }
  }
}
