package ee.schimke.composeai.daemon

import ee.schimke.composeai.daemon.RecordingTestGenerator.Step
import ee.schimke.composeai.daemon.protocol.RecordingScriptEvent
import ee.schimke.composeai.daemon.protocol.SemanticsInputTarget
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class RecordingTestGeneratorTest {

  private fun spec(steps: List<Step>) =
    RecordingTestGenerator.Spec(
      className = "T",
      methodName = "m",
      composableInvocation = "P()",
      steps = steps,
    )

  @Test
  fun generatesAStableTestFromTestTagClicksAndProbes() {
    val source =
      RecordingTestGenerator.generate(
        RecordingTestGenerator.Spec(
          className = "GeneratedTogglePreviewTest",
          methodName = "togglePreviewInteraction",
          composableInvocation = "TogglePreview()",
          packageName = "com.example",
          steps =
            RecordingTestGenerator.stepsOf(
              listOf(
                RecordingScriptEvent(
                  tMs = 0L,
                  kind = "input.click",
                  target = SemanticsInputTarget(testTag = "submit"),
                ),
                RecordingScriptEvent(tMs = 400L, kind = "recording.probe", label = "after-click"),
              )
            ),
        )
      )

    val expected =
      """
      package com.example

      import androidx.compose.ui.test.junit4.createComposeRule
      import androidx.compose.ui.test.onNodeWithTag
      import androidx.compose.ui.test.onNodeWithText
      import androidx.compose.ui.test.performClick
      import org.junit.Rule
      import org.junit.Test

      // Generated by compose-preview from a record_preview interaction (issue #1786).
      // Confirm the setContent call below and add the composable's import before running
      // (named/variant previews share their base @Composable function).
      // Fill in the assertions marked TODO at each recording.probe marker.
      class GeneratedTogglePreviewTest {

        @get:Rule val composeTestRule = createComposeRule()

        @Test
        fun togglePreviewInteraction() {
          composeTestRule.setContent { TogglePreview() }
          composeTestRule.onNodeWithTag("submit").performClick()
          // TODO assert state at probe "after-click"
        }
      }
      """
        .trimIndent() + "\n"

    assertEquals(expected, source)
  }

  @Test
  fun textTargetUsesOnNodeWithText() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          RecordingTestGenerator.stepsOf(
            listOf(
              RecordingScriptEvent(
                tMs = 0L,
                kind = "input.click",
                target = SemanticsInputTarget(text = "Add to cart"),
              )
            )
          )
        )
      )
    assertTrue(
      source,
      source.contains("composeTestRule.onNodeWithText(\"Add to cart\").performClick()"),
    )
  }

  @Test
  fun pixelOnlyClickBecomesAReRecordHint() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          RecordingTestGenerator.stepsOf(
            listOf(RecordingScriptEvent(tMs = 0L, kind = "input.click", pixelX = 12, pixelY = 8))
          )
        )
      )
    assertTrue(
      source,
      source.contains("// click at (12, 8) — re-record with a testTag/role target"),
    )
  }

  @Test
  fun unsupportedTargetBecomesASkippedCommentNotAClick() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          listOf(
            Step(
              RecordingScriptEvent(
                tMs = 0L,
                kind = "input.click",
                target = SemanticsInputTarget(testTag = "missing"),
              ),
              applied = false,
            )
          )
        )
      )
    assertFalse(
      "must not emit a performClick for an unresolved target\n$source",
      source.contains("performClick()"),
    )
    assertTrue(
      source,
      source.contains(
        "// input.click testTag=missing — not resolved during the recording; step skipped"
      ),
    )
  }

  @Test
  fun eventsAreEmittedInTimeOrderAndUnknownKindsAnnotated() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          RecordingTestGenerator.stepsOf(
            listOf(
              RecordingScriptEvent(tMs = 500L, kind = "input.keyDown", keyCode = "29"),
              RecordingScriptEvent(
                tMs = 0L,
                kind = "input.click",
                target = SemanticsInputTarget(testTag = "first"),
              ),
            )
          )
        )
      )
    val clickIdx = source.indexOf("onNodeWithTag(\"first\")")
    val keyIdx = source.indexOf("input.keyDown")
    assertTrue("click (tMs=0) must precede keyDown (tMs=500)\n$source", clickIdx in 0 until keyIdx)
    assertTrue(source, source.contains("// input.keyDown — not yet generated"))
  }
}
