package ee.schimke.composeai.daemon

import ee.schimke.composeai.daemon.RecordingTestGenerator.Step
import ee.schimke.composeai.daemon.protocol.RecordingProbeNode
import ee.schimke.composeai.daemon.protocol.RecordingScriptEvent
import ee.schimke.composeai.daemon.protocol.SemanticsInputTarget
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class RecordingTestGeneratorTest {

  private fun spec(steps: List<Step>) =
    RecordingTestGenerator.Spec(
      className = "T",
      methodName = "m",
      composableInvocation = "P()",
      steps = steps,
    )

  @Test
  fun generatesAStableTestFromTestTagClicksAndProbes() {
    val source =
      RecordingTestGenerator.generate(
        RecordingTestGenerator.Spec(
          className = "GeneratedTogglePreviewTest",
          methodName = "togglePreviewInteraction",
          composableInvocation = "TogglePreview()",
          packageName = "com.example",
          steps =
            RecordingTestGenerator.stepsOf(
              listOf(
                RecordingScriptEvent(
                  tMs = 0L,
                  kind = "input.click",
                  target = SemanticsInputTarget(testTag = "submit"),
                ),
                RecordingScriptEvent(tMs = 400L, kind = "recording.probe", label = "after-click"),
              )
            ),
        )
      )

    val expected =
      """
      package com.example

      import androidx.compose.ui.test.junit4.createComposeRule
      import androidx.compose.ui.test.onNodeWithTag
      import androidx.compose.ui.test.onNodeWithText
      import androidx.compose.ui.test.performClick
      import org.junit.Rule
      import org.junit.Test

      // Generated by compose-preview from a record_preview interaction (issue #1786).
      // Confirm the setContent call below and add the composable's import before running
      // (named/variant previews share their base @Composable function).
      // Fill in the assertions marked TODO at each recording.probe marker.
      class GeneratedTogglePreviewTest {

        @get:Rule val composeTestRule = createComposeRule()

        @Test
        fun togglePreviewInteraction() {
          composeTestRule.setContent { TogglePreview() }
          composeTestRule.onNodeWithTag("submit").performClick()
          // TODO assert state at probe "after-click"
        }
      }
      """
        .trimIndent() + "\n"

    assertEquals(expected, source)
  }

  @Test
  fun probeSemanticsBecomeInferredAssertions() {
    // Two clicks, each followed by a probe carrying the live semantics snapshot. The first probe
    // has no prior snapshot to diff against, so it asserts the test-tagged anchor exists. The
    // second diffs against the first: the "2 items" text appeared and "1 item" disappeared.
    val source =
      RecordingTestGenerator.generate(
        RecordingTestGenerator.Spec(
          className = "GeneratedCartPreviewTest",
          methodName = "cartPreviewInteraction",
          composableInvocation = "CartPreview()",
          packageName = "com.example",
          steps =
            listOf(
              Step(
                RecordingScriptEvent(
                  tMs = 0L,
                  kind = "input.click",
                  target = SemanticsInputTarget(testTag = "addItem"),
                )
              ),
              Step(
                RecordingScriptEvent(tMs = 100L, kind = "recording.probe", label = "after-add"),
                probeSemantics =
                  listOf(
                    RecordingProbeNode(testTag = "cart", clickable = true),
                    RecordingProbeNode(text = "1 item"),
                  ),
              ),
              Step(
                RecordingScriptEvent(
                  tMs = 200L,
                  kind = "input.click",
                  target = SemanticsInputTarget(testTag = "addItem"),
                )
              ),
              Step(
                RecordingScriptEvent(
                  tMs = 300L,
                  kind = "recording.probe",
                  label = "after-second-add",
                ),
                probeSemantics =
                  listOf(
                    RecordingProbeNode(testTag = "cart", clickable = true),
                    RecordingProbeNode(text = "2 items"),
                  ),
              ),
            ),
        )
      )

    val expected =
      """
      package com.example

      import androidx.compose.ui.test.junit4.createComposeRule
      import androidx.compose.ui.test.assertDoesNotExist
      import androidx.compose.ui.test.assertExists
      import androidx.compose.ui.test.onNodeWithContentDescription
      import androidx.compose.ui.test.onNodeWithTag
      import androidx.compose.ui.test.onNodeWithText
      import androidx.compose.ui.test.performClick
      import org.junit.Rule
      import org.junit.Test

      // Generated by compose-preview from a record_preview interaction (issue #1786).
      // Confirm the setContent call below and add the composable's import before running
      // (named/variant previews share their base @Composable function).
      // Probe assertions are inferred from the captured semantics — review them.
      class GeneratedCartPreviewTest {

        @get:Rule val composeTestRule = createComposeRule()

        @Test
        fun cartPreviewInteraction() {
          composeTestRule.setContent { CartPreview() }
          composeTestRule.onNodeWithTag("addItem").performClick()
          // probe "after-add" — assertions inferred from captured semantics
          composeTestRule.onNodeWithTag("cart").assertExists()
          composeTestRule.onNodeWithTag("addItem").performClick()
          // probe "after-second-add" — assertions inferred from captured semantics
          composeTestRule.onNodeWithText("2 items").assertExists()
          composeTestRule.onNodeWithText("1 item").assertDoesNotExist()
        }
      }
      """
        .trimIndent() + "\n"

    assertEquals(expected, source)
  }

  @Test
  fun probeWithNoAssertableSemanticsFallsBackToStub() {
    // A probe whose snapshot has no stable finder (no testTag/text/contentDescription) can't be
    // turned into an assertion — it must still mark the spot with the TODO stub.
    val source =
      RecordingTestGenerator.generate(
        spec(
          listOf(
            Step(
              RecordingScriptEvent(tMs = 0L, kind = "recording.probe", label = "blank"),
              probeSemantics = listOf(RecordingProbeNode(role = "Button")),
            )
          )
        )
      )
    assertTrue(source, source.contains("// TODO assert state at probe \"blank\""))
    assertFalse(source, source.contains("assertExists()"))
  }

  @Test
  fun textTargetUsesOnNodeWithText() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          RecordingTestGenerator.stepsOf(
            listOf(
              RecordingScriptEvent(
                tMs = 0L,
                kind = "input.click",
                target = SemanticsInputTarget(text = "Add to cart"),
              )
            )
          )
        )
      )
    assertTrue(
      source,
      source.contains("composeTestRule.onNodeWithText(\"Add to cart\").performClick()"),
    )
  }

  @Test
  fun pixelOnlyClickBecomesAReRecordHint() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          RecordingTestGenerator.stepsOf(
            listOf(RecordingScriptEvent(tMs = 0L, kind = "input.click", pixelX = 12, pixelY = 8))
          )
        )
      )
    assertTrue(
      source,
      source.contains("// click at (12, 8) — re-record with a testTag/role target"),
    )
  }

  @Test
  fun unsupportedTargetBecomesASkippedCommentNotAClick() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          listOf(
            Step(
              RecordingScriptEvent(
                tMs = 0L,
                kind = "input.click",
                target = SemanticsInputTarget(testTag = "missing"),
              ),
              applied = false,
            )
          )
        )
      )
    assertFalse(
      "must not emit a performClick for an unresolved target\n$source",
      source.contains("performClick()"),
    )
    assertTrue(
      source,
      source.contains(
        "// input.click testTag=missing — not resolved during the recording; step skipped"
      ),
    )
  }

  @Test
  fun eventsAreEmittedInTimeOrderAndUnknownKindsAnnotated() {
    val source =
      RecordingTestGenerator.generate(
        spec(
          RecordingTestGenerator.stepsOf(
            listOf(
              RecordingScriptEvent(tMs = 500L, kind = "input.keyDown", keyCode = "29"),
              RecordingScriptEvent(
                tMs = 0L,
                kind = "input.click",
                target = SemanticsInputTarget(testTag = "first"),
              ),
            )
          )
        )
      )
    val clickIdx = source.indexOf("onNodeWithTag(\"first\")")
    val keyIdx = source.indexOf("input.keyDown")
    assertTrue("click (tMs=0) must precede keyDown (tMs=500)\n$source", clickIdx in 0 until keyIdx)
    assertTrue(source, source.contains("// input.keyDown — not yet generated"))
  }

  // --- defaultSpec: identifier derivation for the record-live bridge (issue #2047) ---

  @Test
  fun defaultSpecUsesCatalogFunctionNameAndPackage() {
    val spec =
      RecordingTestGenerator.defaultSpec(
        previewId = "com.example.WeatherForecast_Light",
        functionName = "WeatherForecast",
        classFqn = "com.example.WeatherScreenKt",
        events =
          listOf(
            RecordingScriptEvent(
              tMs = 0L,
              kind = "input.click",
              target = SemanticsInputTarget(testTag = "refresh"),
            )
          ),
      )
    assertEquals("GeneratedWeatherForecastTest", spec.className)
    assertEquals("weatherForecastInteraction", spec.methodName)
    // Load-bearing for named/variant previews: invocation is the real function, not the id suffix.
    assertEquals("WeatherForecast()", spec.composableInvocation)
    assertEquals("com.example", spec.packageName)

    val source = RecordingTestGenerator.generate(spec)
    assertTrue(source, source.contains("setContent { WeatherForecast() }"))
    assertTrue(source, source.contains("onNodeWithTag(\"refresh\").performClick()"))
  }

  @Test
  fun defaultSpecFallsBackToSanitizedPreviewIdWhenCatalogMisses() {
    val spec =
      RecordingTestGenerator.defaultSpec(
        previewId = "com.example.TogglePreview#dark",
        functionName = null,
        classFqn = null,
        events = emptyList(),
      )
    assertEquals("GeneratedTogglePreviewTest", spec.className)
    assertEquals("togglePreviewInteraction", spec.methodName)
    assertEquals("TogglePreview()", spec.composableInvocation)
    assertEquals(null, spec.packageName)
  }

  @Test
  fun defaultSpecHonoursExplicitOverrides() {
    val spec =
      RecordingTestGenerator.defaultSpec(
        previewId = "com.example.Foo",
        functionName = "Foo",
        classFqn = "com.example.FooKt",
        events = emptyList(),
        classNameOverride = "MyTest",
        methodNameOverride = "myFlow",
        composableInvocationOverride = "Foo(modifier = Modifier)",
        packageNameOverride = "com.acme.test",
      )
    assertEquals("MyTest", spec.className)
    assertEquals("myFlow", spec.methodName)
    assertEquals("Foo(modifier = Modifier)", spec.composableInvocation)
    assertEquals("com.acme.test", spec.packageName)
  }
}
