package ee.schimke.composeai.daemon

import ee.schimke.composeai.daemon.protocol.InteractiveInputParams

/**
 * Held-scene interactive session for one `frameStreamId` — see
 * [INTERACTIVE.md § 9](../../../../../../docs/daemon/INTERACTIVE.md#9-v2--click-dispatch-into-composition).
 *
 * Backends that support interactive mode (today: `:daemon:desktop`'s `DesktopInteractiveSession`,
 * landing in PR 2) implement this interface to keep an `ImageComposeScene` (or per-host equivalent)
 * warm across `interactive/input` notifications. State derived from `remember { mutableStateOf(...)
 * }` survives between [dispatch] calls, so a click that flips a `mutableStateOf` re-paints the
 * composition the next time [render] runs.
 *
 * Lifecycle owned by [JsonRpcServer]:
 * - **Allocate** at `interactive/start` via [RenderHost.acquireInteractiveSession]. Each session
 *   owns a fresh scene; concurrent streams targeting the same preview can either share one session
 *   (host's call — matches the design doc's "one session per previewId" preference) or hold their
 *   own, transparent to this interface.
 * - **Drive** at `interactive/input` — [dispatch] feeds the pointer/key event into the held scene,
 *   then [render] encodes the next frame.
 * - **Release** at `interactive/stop` (or daemon shutdown) — [close] frees the scene and any native
 *   resources.
 *
 * **Threading.** Implementations may assume calls are serialised per-instance — `JsonRpcServer`
 * dispatches inputs from its render-watcher thread, one at a time per session. Concurrent calls to
 * different session instances are independent and may happen on different threads.
 *
 * **No-mid-render-cancellation invariant** ([DESIGN.md §
 * 9](../../../../../../docs/daemon/DESIGN.md)). [close] must drain any in-flight render before
 * tearing down the scene, the same way `RenderHost.shutdown` drains its queue. We never interrupt a
 * render mid-flight.
 */
interface InteractiveSession : AutoCloseable {

  /** The preview id this session is rendering. Frozen at allocation time. */
  val previewId: String

  /**
   * Feed one wire-level [InteractiveInputParams] (click, pointer down/up, key down/up) into the
   * held composition. Implementations translate the protocol-level kind into the host's pointer-
   * input dispatch (e.g. `ImageComposeScene.sendPointerEvent` on desktop), splitting `CLICK` into
   * Press+Release at the same position. Image-natural pixel coords on the wire are scaled by scene
   * density before dispatch.
   *
   * Does NOT render — call [render] afterwards to encode the next frame. The split lets the
   * coalescing path in [JsonRpcServer.handleInteractiveInput] queue several inputs and dispatch
   * them in a batch followed by a single [render].
   */
  fun dispatch(input: InteractiveInputParams)

  /**
   * Render the current composition to a PNG and return the result. The implementation runs the
   * scene through enough frames to settle (typically two `scene.render()` calls — same heuristic as
   * the one-shot path) and encodes to disk at a stable path the daemon can publish via
   * `renderFinished.pngPath`. The session retains the scene; this method is callable repeatedly.
   *
   * @param requestId opaque id forwarded to [RenderResult.id] so the caller's render-watcher can
   *   demux concurrent renders. Generated by `RenderHost.nextRequestId()` at the call site.
   * @param advanceTimeMs optional backend-specific virtual-clock advance before capture. Normal
   *   interactive callers leave this null so the backend uses its default settle window; recording
   *   callers can pass frame deltas to keep captured animation time paced to fps.
   */
  fun render(requestId: Long, advanceTimeMs: Long? = null): RenderResult

  /**
   * Drains any in-flight render, frees the held scene + its native resources, and removes any
   * filesystem state owned by the session (e.g. the per-stream PNG output file). Idempotent —
   * subsequent calls are no-ops. Safe to call from the daemon's shutdown drain even when an input
   * is queued.
   */
  override fun close()
}
