package ee.schimke.composeai.daemon

import ee.schimke.composeai.daemon.protocol.RecordingScriptEvent
import ee.schimke.composeai.daemon.protocol.SemanticsInputTarget

/**
 * Turns a `record_preview` script timeline into a runnable Compose UI test (issue #1786) — the
 * Compose analogue of Playwright's `codegen`. The recorded exploration becomes durable regression
 * coverage: each pointer event that carried a semantic target (issue #1784) emits a stable
 * `onNodeWith…().performClick()` step rather than a pixel coordinate, and each `recording.probe`
 * marker becomes a labelled assertion stub the author fills in.
 *
 * Steps are built from what the recording **actually did**: a [Step] whose `applied` is false (the
 * daemon reported `unsupported` script evidence — e.g. a target that matched no node) is emitted as
 * a skipped-step comment, never a `performClick`, so the generated test reflects the captured flow.
 *
 * Pure string generation — no Compose / daemon runtime — so it is golden-testable in isolation. The
 * "infer the assertion at each probe from the captured semantics" half of #1786 is intentionally a
 * follow-up; the probe stubs mark exactly where those assertions go.
 */
object RecordingTestGenerator {

  /** One recorded event plus whether the recording reported it as applied (vs `unsupported`). */
  data class Step(val event: RecordingScriptEvent, val applied: Boolean = true)

  /** Inputs for one generated test. */
  data class Spec(
    /** Generated class name, e.g. `GeneratedTogglePreviewTest`. */
    val className: String,
    /** Generated `@Test` method name, e.g. `togglePreviewInteraction`. */
    val methodName: String,
    /** Composable call placed in `setContent { … }`, e.g. `TogglePreview()`. */
    val composableInvocation: String,
    /** Optional package declaration for the generated file. */
    val packageName: String? = null,
    val steps: List<Step>,
  )

  /** Wrap raw events as all-applied steps — for callers without recording evidence. */
  fun stepsOf(events: List<RecordingScriptEvent>): List<Step> = events.map { Step(it) }

  fun generate(spec: Spec): String = buildString {
    spec.packageName?.takeIf { it.isNotBlank() }?.let { appendLine("package $it").appendLine() }
    appendLine("import androidx.compose.ui.test.junit4.createComposeRule")
    appendLine("import androidx.compose.ui.test.onNodeWithTag")
    appendLine("import androidx.compose.ui.test.onNodeWithText")
    appendLine("import androidx.compose.ui.test.performClick")
    appendLine("import org.junit.Rule")
    appendLine("import org.junit.Test")
    appendLine()
    appendLine("// Generated by compose-preview from a record_preview interaction (issue #1786).")
    appendLine(
      "// Confirm the setContent call below and add the composable's import before running"
    )
    appendLine("// (named/variant previews share their base @Composable function).")
    appendLine("// Fill in the assertions marked TODO at each recording.probe marker.")
    appendLine("class ${spec.className} {")
    appendLine()
    appendLine("  @get:Rule val composeTestRule = createComposeRule()")
    appendLine()
    appendLine("  @Test")
    appendLine("  fun ${spec.methodName}() {")
    appendLine("    composeTestRule.setContent { ${spec.composableInvocation} }")
    spec.steps.sortedBy { it.event.tMs }.forEach { step -> appendStep(step) }
    appendLine("  }")
    append("}")
    appendLine()
  }

  private fun StringBuilder.appendStep(step: Step) {
    val event = step.event
    when {
      event.kind == "input.click" && !step.applied ->
        appendLine(
          "    // input.click ${describeTarget(event)} — not resolved during the recording; " +
            "step skipped"
        )
      event.kind == "input.click" -> appendLine("    ${clickStep(event)}")
      event.kind == "recording.probe" -> appendLine("    ${probeStep(event)}")
      else ->
        appendLine(
          "    // ${event.kind}${event.label?.let { " \"$it\"" } ?: ""} — not yet generated; " +
            "drive it by hand"
        )
    }
  }

  private fun clickStep(event: RecordingScriptEvent): String {
    val selector = nodeSelector(event.target)
    if (selector != null) return "composeTestRule.$selector.performClick()"
    val x = event.pixelX
    val y = event.pixelY
    return if (x != null && y != null) {
      "// click at ($x, $y) — re-record with a testTag/role target for a stable, " +
        "coordinate-free step"
    } else {
      "// click — no target or coordinates recorded; cannot generate a step"
    }
  }

  /** Map a semantic target onto the strongest available Compose test finder. */
  private fun nodeSelector(target: SemanticsInputTarget?): String? {
    if (target == null) return null
    target.testTag
      ?.takeIf { it.isNotBlank() }
      ?.let {
        return "onNodeWithTag(${it.quote()})"
      }
    target.text
      ?.takeIf { it.isNotBlank() }
      ?.let {
        return "onNodeWithText(${it.quote()})"
      }
    // ref / role alone have no direct Compose-test finder; surface them so the author can refine.
    return null
  }

  private fun describeTarget(event: RecordingScriptEvent): String {
    val t = event.target ?: return "(no target)"
    return listOfNotNull(
        t.testTag?.let { "testTag=$it" },
        t.role?.let { "role=$it" },
        t.text?.let { "text=\"$it\"" },
        t.ref?.let { "ref=$it" },
      )
      .joinToString(" ")
      .ifBlank { "(no target)" }
  }

  private fun probeStep(event: RecordingScriptEvent): String {
    val label = event.label?.takeIf { it.isNotBlank() }
    return "// TODO assert state${label?.let { " at probe \"$it\"" } ?: ""}"
  }

  private fun String.quote(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
